// Generated by CoffeeScript 1.10.0
(function() {
  Function.delay = function(amount, procedure, data) {
    return setTimeout((function() {
      return procedure(data);
    }), amount);
  };

}).call(this);
